import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use – QuickCalcs",
  description:
    "Terms and conditions for using QuickCalcs free online calculator tools.",
};

export default function TermsOfUsePage() {
  return (
    <div className="bg-[#0c0e16] text-[#c9c6be]">
      <div className="max-w-[780px] mx-auto px-5 sm:px-9 py-20">
        {/* Top label */}
        <span className="text-[#c9a84c] text-sm font-semibold">Legal</span>

        {/* Page title */}
        <h1 className="mt-2 text-3xl font-bold text-white">Terms of Use</h1>
        <p className="text-[#87847d] mt-1">Effective date: January 1, 2026</p>

        <div className="space-y-12 mt-8">
          {/* Acceptance of Terms */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Acceptance of Terms
            </h2>
            <p>
              By accessing or using QuickCalcs at https://www.quickcalcs.app, you agree to be bound by these Terms of Use. If you do not agree, please discontinue use immediately.
            </p>
          </section>

          {/* Use of Tools & Calculators */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Use of Tools &amp; Calculators
            </h2>
            <p>
              All calculators and tools on QuickCalcs are provided for informational and reference purposes only. Results generated by any tool — including Gold Calculator, Zakat Calculator, UAE Gratuity Calculator, and others — do not constitute financial, legal, tax, or professional advice. Users should consult a qualified professional before making any financial decisions based on calculator results. QuickCalcs assumes no responsibility for decisions made based on tool outputs.
            </p>
          </section>

          {/* Intellectual Property */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Intellectual Property
            </h2>
            <p>
              All content on QuickCalcs — including but not limited to text, code, design, layout, logos, and tool logic — is the intellectual property of QuickCalcs. You may not copy, reproduce, distribute, or create derivative works without explicit written permission.
            </p>
          </section>

          {/* Disclaimer of Warranties */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Disclaimer of Warranties
            </h2>
            <p>
              QuickCalcs tools are provided "as is" without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of any calculator result. Rates and values (such as live gold prices) may not reflect real‑time market data and should be independently verified.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by law, QuickCalcs shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of or inability to use the site or its tools — including any financial loss resulting from reliance on calculator outputs.
            </p>
          </section>

          {/* Advertising &amp; Third‑Party Content */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Advertising &amp; Third‑Party Content
            </h2>
            <p>
              QuickCalcs displays advertisements served by Google AdSense and other third‑party networks. We are not responsible for the content, accuracy, or privacy practices of any advertised third‑party websites. Clicking on advertisements is at your own discretion.
            </p>
          </section>

          {/* User Conduct */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              User Conduct
            </h2>
            <p>
              You agree not to misuse the site in any way, including attempting to reverse‑engineer tools, scrape content, introduce malware, or use automated bots.
            </p>
          </section>

          {/* Changes to Terms */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these Terms of Use at any time. Changes will be posted on this page with an updated effective date. Continued use of the site after changes constitutes acceptance of the new terms.
            </p>
          </section>

          {/* Governing Law */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Governing Law
            </h2>
            <p>
              These terms shall be governed by and construed in accordance with the laws of the United Arab Emirates. Any disputes shall be subject to the exclusive jurisdiction of the courts of the UAE.
            </p>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-lg font-semibold text-white border-b border-[rgba(255,255,255,0.07)] pb-3 mb-4">
              Contact
            </h2>
            <div className="border border-[rgba(201,168,76,0.3)] rounded-xl p-5 bg-[rgba(255,255,255,0.03)]">
              <p className="font-bold text-white">QuickCalcs</p>
              <p>
                Website:{' '}
                <a
                  href="https://www.quickcalcs.app"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#c9a84c] hover:underline"
                >
                  https://www.quickcalcs.app
                </a>
              </p>
              <p>
                Email:{' '}
                <a
                  href="mailto:legal@quickcalcs.app"
                  className="text-[#c9a84c] hover:underline"
                >
                  legal@quickcalcs.app
                </a>
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}